
export const icons: Record<string, string> = {
    Button: "symbol-string",
    CheckBox: "check",
    ColumnLayout: "layout-centered",
    Configurator: "checklist",
    ExpansionPanel: "expand-all",
    HorizontalSlider: "chrome-minimize",
    Image: "device-camera",
    Label: "tag",
    List: "list-unordered",
    NumberSpinner: "symbol-operator",
    OpenObjectButton: "symbol-misc",
    PasswordTextBox: "workspace-unknown",
    PopupAlert: "comment-unresolved",
    PopupButton: "comment",
    ProgressBar: "rocket",
    QrCode: "circuit-board",
    RowLayout: "layout-panel",
    ScriptEditor: "code",
    Select: "tasklist",
    SelectAction: "debug-stackframe-active",
    SelectCategory: "folder",
    SelectColor: "symbol-color",
    SelectCondition: "pass",
    SelectDate: "calendar",
    SelectDateTime: "calendar",
    SelectEvent: "symbol-event",
    SelectFile: "file",
    SelectIcon: "device-camera",
    SelectInstance: "inspect",
    SelectLink: "link",
    SelectLocation: "location",
    SelectMedia: "file-media",
    SelectModule: "symbol-method",
    SelectObject: "file-binary",
    SelectProfile: "mention",
    SelectScript: "file-code",
    SelectTime: "calendar",
    SelectValue: "activate-breakpoints",
    SelectVariable: "symbol-variable",
    StatusMessage: "note",
    TestCenter: "terminal-powershell",
    Tree: "list-tree",
    ValidationTextBox: "symbol-string",
} as const;

